apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nvidia-device-plugin
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: nvidia-device-plugin
      version: 0.17.0
      sourceRef:
        kind: HelmRepository
        name: nvidia-dvp
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    image:
      repository: nvcr.io/nvidia/k8s-device-plugin
      tag: v0.17.0
    runtimeClassName: nvidia
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - "gpu-worker-1"
                    - "gpu-worker-2"

    config:
      map:
        default: |-
          version: v1
          sharing:
            timeSlicing:
              renameByDefault: false
              resources:
                - name: nvidia.com/gpu
                  replicas: 4
