apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:Nk9djLviJECDoR3pCctNqXtuM3QX5b6H422uI8PxjfE=,iv:HFkphyk4lMGVLpv3wmrRHqGqRb7dKgEMxi/pXMXmW6o=,tag:LBjNrGl2aMgqHYzT26ZQEA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gdvr6gczkcnzysfefvql83kczuc2nwpfxdq5yvdvlmgwa4pfkgnqgk87pp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrakdKSm9tRmNlSXk1Tk5P
            dXJxSlVGRU9LUUVHZ2hVSEJvQUYzZWlPNW44CkszbzZLUy9ObjY3blY3Ry9lVGdE
            REdZbHpuWHJmYW9jek1CUG1NSXd4aHMKLS0tIGtNb0NKelVNRndsQURLWkxVTWp6
            L2k1NzZLL2tUWStxV2g1YkxhRjdlSFUKOkS89ltP/pJu+1uFy5li2UqGeptLafnZ
            /wrp0hpxu7MzUYc8xxF7WP0jq+KTAZzJOGB+S3QRXNGXnTCeKIihtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-18T03:02:06Z"
    mac: ENC[AES256_GCM,data:GFE3HOPSRXFi8VJ5o0yEvO8i4YYwn5ZPu6F/fc5VLWwGVPfqIc1PJnllI5DCptcbX1v027sWDKtl0HM0lLW5JTs/AkWmke5DVlSoGP8rH3yMaaJsXO8jNbY2WIOKg4eo97qpqikdvGdO5quY1hgbrVogUp8eTs8P2H5FIL/oaBA=,iv:6gDNB+YU/1Z75wTwwD8i0EAV3axGYVnn2GHShmYys4M=,tag:cVEXwmVNuq1ySqu43qoftA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
