apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:auXei+xzX7AeJe8v5eo8qCWY4ubs7N0Mg73uooe9ccs=,iv:nPzInfaou0oLRh5kjK9nVKyyKaJlw/GjwvZNptuiZok=,tag:9AXYmlbQL8zSSwZHqt2FSA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gdvr6gczkcnzysfefvql83kczuc2nwpfxdq5yvdvlmgwa4pfkgnqgk87pp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpYUtZNTZlbmx3VmE5aFlF
            VHR2U3RTSGpLL3RCc29iU3RHaUk5M0hhSkQ4Ckt0N1lYQ2Q1aEdoMDdFam9rbXpL
            clNDZnkxMUJBWDRzM2VuRDlNQ1JjUWMKLS0tIDRrUjhrYlErZVk1cGpYSEpabUsr
            YUNqc0ViSlQrekpqZmZ5TFFsUTQ0NEUKtPDtmXsPXARhZJEDexFCKH+kLEt97U4J
            1B3hYp2RPfHv26q+uuROVPzym7qrsJ7zpMiprcn+DdWw48AbtoYvcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-20T22:25:13Z"
    mac: ENC[AES256_GCM,data:v6bYJzutVmEmLeFOy2ls8TuRJcl247xplK+o2Q71QJ37jQ+w+vdBia/pK8NukOPEMTjRMtg8mAOTV2ro/2T3SgnalwUSZgGCUK/IqylPfBdf+2M1tkxjf68HUll7B4CGjIxi51UqWnepXwjRaZiiexiPxO0P+/iAeXn/o/W83oo=,iv:Y8Vd0JdJ1jvFiwa4vneG0vKsFm3ANVy2rRE9PIkcHAY=,tag:6omx8fNV/aLY6LLT6586Pg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
